### ISSUE TITLE
COVID example

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/ods#143]
We are always looking for good example for the ODS. Covid is a good one - we already have an example using the Covid JSON API. However, let's evaluate if we can also make use of the raw data lying on GitHub: https://github.com/CSSEGISandData/COVID-19

**Comment by lunedis** [comment]
Is this closed by https://github.com/jvalue/corona-check ?

**Comment by georg-schwarz** [comment]
Jep, thanks @lunedis
