### ISSUE TITLE
Update architecture overview in README

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#146]
The architecture overview figure in README.md still contains the core, which has been removed in pr #145. We should create a new figure.

**Comment by georg-schwarz** [comment]
Suggestion:

![Event-Driven-Microservices(1)](https://user-images.githubusercontent.com/28054628/94148286-b7b65f80-fe76-11ea-8fe6-1bf8c8bf13b5.png)

Thoughts?

**Comment by andreas-bauer** [comment]
- The VUE box on the left side contains a label `Text`.
- The HTTP label between client and server should be above the line
- I would remove the legend on the right side with the alternative names, or would change the text to 'previous name'
- I would like to see the URLs above the different boxes, for example,  `localhost:8080/api` above the gateway or `/dataservice` above the Datasource-Service. But I'm not sure if this diagram is the right place for it or if this information should be presented a another place. For the message broker you also listen the queue names.

Apart from these points the diagram looks good. 😃

**Comment by mathiaszinnen** [comment]
I am not sure whether we should include the topic and queue bindings in the amqp overview. To be precise, the publishing services do not know anything about the consuming queues, so maybe we should depict the topic exchange and the queue bindings as well, like [here](https://www.cloudamqp.com/blog/2015-09-03-part4-rabbitmq-for-beginners-exchanges-routing-keys-bindings.html#topic-exchange). 
I don't know if this makes the diagram too complex but I have a feeling that it would make it much easier to understand how we use rabbitmq.

**Comment by georg-schwarz** [comment]
Thanks for the feedback!
I agree with the routing, that this might not be the right place, same for having exact pub/sub names.
Bringing in the queues is somewhat problematic, I agree. I will give it another shot ;)

**Comment by georg-schwarz** [comment]
![Event-Driven-Microservices](https://user-images.githubusercontent.com/28054628/94165975-12f24d00-fe8b-11ea-8801-0ac433f88241.png)

**Comment by sonallux** [comment]
Looks great! Just one minor issue the two subscribe arrows from `topic:datasource.config.*` and `topic:datasource.import.*` to the Pipeline-Service are both on top of each other.

**Comment by georg-schwarz** [comment]
![Event-Driven-Microservices(2)](https://user-images.githubusercontent.com/28054628/94238263-6490eb00-ff10-11ea-958c-20ecef5b4f0d.png)

**Comment by mathiaszinnen** [comment]
Nice, I like it!
