### ISSUE TITLE
Validation in Adapter API

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#156]
When creating/updating datasources in the `adapter/datasources` API, validation does not work as expected (e.g. posting a datasource with protocol type "LOL" does not trigger malformed request).
When trying to trigger an import for a malformed datasource with the `datasources/{id}/trigger` endpoint, all exceptions that occur while importing are mapped to Http 404 responses. 
We should refactor input validation for datasource management and exception handling for the trigger part.

**Comment by sonallux** [comment]
This can be closed, as the two main points of this issue have been resolved in #231 and #235.
