### ISSUE TITLE
Adapter IT failing occasionally

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#179]
Reason unclear

**Comment by mathiaszinnen** [comment]
I have a hunch that it is a timing issue related to rabbitmq

**Comment by georg-schwarz** [comment]
Only in CI or also locally?

**Comment by mathiaszinnen** [comment]
Up to now, I was not able to reproduce that locally

**Comment by mathiaszinnen** [comment]
fixed by introducing a startup delay in the integration test
