### ISSUE TITLE
Remove http pipeline trigger endpoint in transformation service?

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#183]
Apart from the integration tests, the http pipeline trigger endpoint in the transformation service is not used anymore. 
We can either 
1) Remove it to keep the service as simple as possible 
2) Keep it to be able to conveniently access the functionality from outside (e.g. for testing and debugging)

I am not sure what I prefer, and I would like to hear your opinions on that @georg-schwarz, @lunedis, @jenswaechtler, @andreas-bauer, @jsone-studios.

**Comment by georg-schwarz** [comment]
I would remove it. 

Rabbitmq admin UI also allows to publish events, so it gives us the same functionality :)

**Comment by andreas-bauer** [comment]
I also would remove it. Two implementations for one functionality will just increase the maintenance effort and will confuse new users.
