### ISSUE TITLE
Remove dataLocation field from pipelineExecutionRequest

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#184]
- [ ] Check if any other service (e.g. UI) uses the `dataLocation` field and change it so we consistently use the `data` field only.
- [ ] Remove the data attribute from pipelineExecutionRequest in transformation service

**Comment by sonallux** [comment]
~@mathiaszinnen Your PR #178 already removes the `dataLocation` field for the amqp **and** rest endpoint. So this issue is useless.~

**Comment by mathiaszinnen** [comment]
I am talking about [this](https://github.com/jvalue/open-data-service/blob/master/transformation/src/api/pipelineExecutionRequest.ts) interface

**Comment by sonallux** [comment]
> I am talking about [this](https://github.com/jvalue/open-data-service/blob/master/transformation/src/api/pipelineExecutionRequest.ts) interface

Oh sorry, I misread the title ...

**Comment by sonallux** [comment]
The `dataLocation` field of the pipelineExecutionEndpoint is nowhere used. I will create a PR to remove this field.
