### ISSUE TITLE
Proposal: Update linter rules

### ISSUE THREAD

**Issue by sonallux** [jvalue/ods#195]
Currently the eslint configs from [eslint-config-standard](https://github.com/standard/eslint-config-standard) and [@typescript-eslint/recommanded](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) are used. Using these two configs has a few drawbacks:

- The rules from `eslint-config-standard` are only designed for plain JavaScript, therefore there are some style inconsistencies with TypeScript (for example semicolons are prohibited everywhere except in interface definitions as they are only available in TypeScript.)
- `@typescript-eslint` rules that would require types checking are currently not enabled, because they are only available in the `@typescript-eslint/recommended-requiring-type-checking` config. Those rules would enforce stricter type checking and would spot many of the current present TypeScript issues in the codebase (Issues similar to #171).

### Possible solutions
1.  Add the `@typescript-eslint/recommended-requiring-type-checking` rule and manually adjust some `eslint` and `@typescript-eslint` rules to align with the `eslint-config-standard`.
    - Stricter rules for types than solution 2.: higher migration cost as some places would need a lot of refactoring
    - Manual configuration of the `@typescript-eslint` rules to align with `eslint-config-standard`

2. Use the [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript). This eslint config is based on the `eslint-config-standard` and enables TypeScript specific rules from `@typescript-eslint`.
    - Less strict rules for types than solution 1., but stricter than the current configuration: lower migration cost, because of less refactoring
    - No manual rule configuration and alignment with `eslint-config-standard`

I would prefer solution 2. as it would be easier to update and we do not need to maintain our config to align with `eslint-config-standard`. If stricter type checking rules from `@typescript-eslint` are desired, we can still add them manually to your configuration.

### Update plan
I think the update must be done in multiple steps, even if updating only one microservice at a time. In each step, I would manually adjust some rules that would align your eslint config more with the desired solution. For example, the first step would be to disable semicolons in interfaces. After a few iterations, we can update your config to only use the rules from the predefined configurations.

As this would be a rather big update, not for features but definitely for code quality, I would like to hear your opinions about my proposal. Feedback and/or suggestions are also very welcome. @georg-schwarz @mathiaszinnen @andreas-bauer @lunedis @jenswaechtler

**Comment by georg-schwarz** [comment]
Agreed, that an iterative process is the right way to go here!

Will the linter rules of solution 2 be a subset of solution 1?

**Comment by sonallux** [comment]
> Will the linter rules of solution 2 be a subset of solution 1?

No, `eslint-config-standard-with-typescript` is just enabling the rules from the `@typescript-eslint/eslint-plugin` the maintainers like. The `@typescript-eslint/recommended-requiring-type-checking` and `@typescript-eslint/recommended` configs are also just enabling a subset of the available rules from `@typescript-eslint/eslint-plugin`.

**Comment by sonallux** [comment]
Every microservice has been updated, therefore this is done and can be closed.
