### ISSUE TITLE
Combine multiple data sources

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#23]
We should enable the combination of data from multiple sources. This can be done either in the adapter service or in the transformation service. I suggest doing it in the latter since data combination is modeled better by a transformation than by an adaptation.

It is probably best to refactor the data flow in the ODS. Currently, a pipeline consists of one adapter, followed by multiple transformations, storage, and optional notifications. That is, in pseudo-EBNF: A T* S N*. What we want are multiple stages of one adapter each followed by one transformation each and in the end optional storage and optional notifications, i.e.: {A T}+ [S] N*. Since the transformations are touring complete, modeling multiple transformations after one adapter is redundant and could be simplified by using just one. If we find out that it is more convenient to split data transformation into multiple parts, we can still offer it in the UI and just concatenate the transformations before passing it to the scheduler. The amse projects revealed that a common use case for the ODS is getting URLs from one source that should be used to get data from another. To enable this process we need a dynamic adapter configuration. The easiest implementation of this should be adding the parameters for subsequent adapters to the data field so they can be used there.

**Comment by dirkriehle** [comment]
I agree that the transformation pipeline is the place for the combination of multiple data source on the source side (there is a separate requirement for combination on the client side, perhaps through GraphQL). It is less clear to me that we should program this or use an established open source library. Didn't we talk about an Apache library that does just that?
