### ISSUE TITLE
Unify used docker images (both base and services)

### ISSUE THREAD

**Issue by lunedis** [jvalue/ods#238]
A quick look over the Dockerfiles and the `docker-compose` file made me realize that we should make sure to use consistent versions of all used docker images.

We seem to be consistent in using `node:lts-alpine` for all node-related containers, but I'd like to double check.

We certainly use different versions of `postgres` (`latest` and `12-alpine`). Is there a reason for that?

Also do we even want to use something like `latest` or `lts-alpine` or rather specify an exact version? What's the best practice here?

**Comment by sonallux** [comment]
IMO, it's best practice to **not** use the `latest` or `lts-alpine` docker tags and instead use a tag with a fixed major version number like `12-alpine`. The docker tags without a major version specified can move to a new major version number without notice. As nearly all projects do follow semantic versioning, such a change in the major version number does contain breaking changes and potentially break the ODS.

For example, the `node:lts-alpine` image we are using for all services has moved from node 12.X to node 14.X just two weeks ago.

**Comment by georg-schwarz** [comment]
I agree we should depend on concrete major versions. We had the issue of things crashing due to version updates!
However, we have to make sure to check regularly for newer versions and upgrade manually. Building up technical depts in that regard is not a good idea as well! Any ideas how we want to handle that? Would it make sense to distribute responsibilities to services for maintaining?

**Comment by MBuchalik** [comment]
> However, we have to make sure to check regularly for newer versions and upgrade manually.

Two ideas:
1. We could write a script that parses all dockerfiles and informs us about major releases. This script could be run manually, or using a cronjob, or... If a new major release is out, it could maybe even open a GitHub Issue. 

2. Use something like Dependabot. Seems like this is natively supported in GitHub: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
One thing I am not sure about:
Such tools often create a new PR for every single dependency update. No matter if it is a major release, or just a patch. So if you depend on something that changes really often, you will get lots of PRs. I don't know if it is possible to configure Dependabot to only inform us about major releases.

**Comment by georg-schwarz** [comment]
Dependabot would be an option, however I think @dirkriehle mentioned that these PRs are legally not to be accepted? But we could use it to inform us somehow, I think it is configurable in some ways..

**Comment by lunedis** [comment]
https://github.com/dependabot/dependabot-core/issues/390

It also seems that dependabot only supports image versions in Dockerfiles, not in `docker-compose` files.

This would mean it would not notify us about updates of e.g. the postgres-versions referenced in only the `docker-compose` files.

**Comment by lunedis** [comment]
In my research I also found [Diun](https://crazymax.dev/diun/). Diun notifies you when a a specific docker tag gets updated, which is not what we want. We want to be notified when the image we use (e.g. `node:12-alpine`) gets deprecated and we want to (manually) switch to e.g. `node:14-alpine`.

Not sure if a software like that exists.

**Comment by georg-schwarz** [comment]
Well, having a quarter annual calendar entry can also fix that, so no worries.. ^^

**Comment by lunedis** [comment]
https://docs.renovatebot.com/modules/manager/docker-compose/

RenovateBot seems to support `docker-compose` files.
