### ISSUE TITLE
Notification: Integration test failing occasionally

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#245]
Reason unclear

**Comment by mathiaszinnen** [comment]
Since I was not able to reproduce the problem locally and it did not occur again I assume it has disappeared magically. Closing the issue. Please reopen if it happens again.

**Comment by mathiaszinnen** [comment]
happened again on the ci

**Comment by sonallux** [comment]
Happened on [this CI run](https://github.com/jvalue/open-data-service/pull/311/checks?check_run_id=1775208956) too
