### ISSUE TITLE
Build: Git's auto conversion of line endings causes build error on Windows os

### ISSUE THREAD

**Issue by Kexplx** [jvalue/ods#259]
When cloning a repository on Windows, git converts all unix line endings (LF) to DOS format (CRLF) by default.
In many projects this isn't important but for the ODS it causes the following error when running `docker-compose up` in the project root (from Windows).

![Code_QxSeFFvzdM](https://user-images.githubusercontent.com/29175032/100172572-e8436580-2ec8-11eb-922e-968a37dc686b.png)

If you don't know about this auto conversion done by git, the error can be quite annoying since line endings are usually hidden.

We should ensure that the instructions from the [Quickstart](https://github.com/jvalue/open-data-service#quick-start) also apply for Windows machines with a default git config.
Let me know if you think is worth a PR.

**Comment by sonallux** [comment]
I can build and run the ODS on Windows without any problems. 

As you mentioned this might be an issue with git converting line endings. The `git config core.autocrlf` is controlling this behaviour. I have set this option to `input`. But unfortunately, I do not know if that is the default or if I have changed it. 

Could you run `git config core.autocrlf` to see what is your configuration?

**Comment by Kexplx** [comment]
Hi Jonas.
Yes, thats one of many fixes. Sadly, `git config core.autocrlf` is set to false by default.
Again, this error only occurs with the **default git config** when running `git clone` without any flags.

I think we should either add a disclaimer in the README or put `Dockerfile text eol=lf` inside a `.gitattributes` file. This would convert CRLF to LF on every checkout.

**Comment by sonallux** [comment]
Well, then I would add a `.gitattributes` file as it just works out of the box.

**Comment by georg-schwarz** [comment]
Thx for your contribution!
Of course, we would welcome a PR to fix this :)

Cheers,
Georg

**Comment by georg-schwarz** [comment]
Closed bz #259
