### ISSUE TITLE
Scheduler can get initialized with wrong state

### ISSUE THREAD

**Issue by sonallux** [jvalue/ods#284]
### Short overview
The scheduler stores a `SchedulingJob` for each datasource in memory. All changes to datasources (addition, update and deletion) are propagated to the scheduler by AMQP messages. The corresponding `SchedulingJob` is then adjusted accordingly, so the scheduler is always triggering the right datasource at the right time. The state of the scheduler is not persistent and therefore it must be reconstructed on every start of the scheduler. Because past datasource change events can not be replayed, the scheduler must query the adapter for the current list of datasources when it is starting. So basically the scheduler must perform two tasks when starting:
1. It must get the current list of datasources from the adapter and create the corresponding `SchedulingJobs`
2. It must start listening for changes to the datasources

If those two tasks are not perfectly aligned to each other, the following problems can occur which can lead to a wrong state in the scheduler:
- Changes can get lost
- Changes are applied in the wrong order
- Changes can get applied twice (Fortunately this does not cause issues, because applying a change in the scheduler is idempotent)

### Current scheduler implementation
Currently, the scheduler first starts listening to the datasource change events and then performs a REST request to the adapter to get the current list of all datasources. But this can lead to changes applied in the wrong order.

This happens because an event consumption can overtake the REST response delivery and creating the initial state. Then the changes are applied in the wrong order leading to a wrong state. There is a schematic visualization of this behavior in the following image. The black arrows are datasource changes, which trigger the datasource change events (green arrows). The blue arrows are the requests for querying the current list of datasources and the corresponding responses. 
![Scheduler-init-1](https://user-images.githubusercontent.com/13821543/101786311-0f6f7900-3afe-11eb-9d6d-e1f9455db1a3.png)

<details><summary><strong>Non-working solution approach</strong></summary>
<p>
One might think this can be solved by changing the order of getting the current state and starting to consume events. But this can cause lost changes:

![Scheduler-init-3](https://user-images.githubusercontent.com/13821543/101786492-48a7e900-3afe-11eb-906d-0e8457b21437.png)

</p>
</details>

### Requirements for a working solution
To get a solution that guarantees consistency is very difficult and complex, so here are the main requirements for a solution:
- All changes to datasources starting at the point when the **adapter** constructed the list of datasources for the response, must arrive at the scheduler
- Events published after the **adapter** has created the current list of datasources, must not be applied before the current list of datasources has been applied

### Simple solution that does not have strong consistency
The following solution can not guarantee strong consistency and in my opinion not even eventual consistency. But that's discussable because at some point it will get to a consistent state:
1. Start listening for datasource change events, but do not yet apply the changes to the scheduler state
2. Request the current state from the adapter
3. Build the initial scheduler state
4. Start applying the changes from events

This works because the order is ensured by waiting and applying a change is idempotent. But this solution does not provide strong consistency. See the following image for an example. After applying the current list of datasources the scheduler state is consistent to the state of the adapter. Then the change of the first event is applied, which can lead to an inconsistent state. Only after applying the second event, the state is consistent again. I would argue this is not even eventual consistent, because an inconsistent state archived after being in a consistent state. The state will become consistent again because we can assume events do not get lost and all event will get consumed at some point in time.
![Scheduler-init-5](https://user-images.githubusercontent.com/13821543/101786556-58bfc880-3afe-11eb-8378-452ad69a7263.png)

### Other solutions
- Send the current state via an event. Ordering is guaranteed by RabbitMQ, if the messages are published on one channel. So the Adapter must ensure that Datasource change events and the current state event is published on the channel in the right order. The Scheduler would then start applying changes from events after consuming the initial state event.
- The Adapter constructs some kind of timestamp for the current state and sends this timestamp with the current state. This timestamp can be used to filter events and only apply events, that have been published after the current state has been created. RabbitMQ has no such feature, but other message/event system might have.
- Discard RabbitMQ and use Kafka so we can build a truly event-sourced system

### The important role of the adapter database
What I have not mentioned till now is that the adapter does not have the current state immediately available, it must always perform a network request to query the adapter-database. And as soon as the database has performed the query the result might be already outdated because another request could have already changed any datasource. The change event for later change can actually be delivered to the scheduler before the result of the first query is delivered to the scheduler. 

This is actually caused by another broader issue the current architecture has for all database, for which data change events are published: The order of the change events might not be equal to the order, in which the changes have been performed by the database. Please see my other issue for more details: #285.

### Conclusion
A nice solution can only be found when fixing the database event ordering issue (#285) first because the current issue is highly dependent on how and when events are published.
For the time being, we could use my simple solution that does hot have strong consistency. But nevertheless, this issue with the initialization of the scheduler must be reevaluated after the database event ordering issue has been fixed.

---

Wow, this got quite long 👀  I hope, I have not lost everyone somewhere in the unreliable network 😆 
If there is anything unclear or I have forgotten something please let me know.

**Comment by georg-schwarz** [comment]
Haha, I like the "Discard RabbitMQ and use Kafka so we can build a truly event-sourced system" approach.

I got feedback from an architect to our architecture, and he basically said the same. Seems like RabbitMQ does not really scale well when having multiple nodes on high-availability guarantees. Another idea I got there was to remove the scheduler and use the Kubernetes [Cronjobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) as soon as we use Kubernetes instead of docker-compose. That would also remove the non-scalable scheduler as a bottleneck.

All these considerations made, I think going for an interim solution is ok since we don't know how infrastructure will change in the new future.

**Comment by sonallux** [comment]
> Seems like RabbitMQ does not really scale well when having multiple nodes on high-availability guarantees.

Well, I do not know if that is really true. You can use [Clustering](https://www.rabbitmq.com/clustering.html) to use more than one machine for RabbitMQ itself (this does not replicate queues) and [QuorumQueues](https://www.rabbitmq.com/quorum-queues.html) for replicating the queues itself. 

I do not think these Kubernetes Cronjobs can be created from inside a container (e.g. the adapter). And it seems that it is not really reliable. Quote from the docs:
> A cron job creates a job object about once per execution time of its schedule. We say "about" because there are certain circumstances where two jobs might be created, or no job might be created. We attempt to make these rare, but do not completely prevent them. Therefore, jobs should be idempotent.

---

> That would also remove the non-scalable scheduler as a bottleneck.

The scheduler can be scaled by sharding. One instance of the scheduler would then only be responsible for a subset of the datasources. This would require some refactoring and a clever mechanism to assign a unique scheduler instance for each datasource.

**Comment by sonallux** [comment]
I have thought about this issue and possible solutions. I came to the conclusion that all mentioned solutions except the one with building a truly event-sourced system do not work and scale well because we are always mixing synchronous REST requests (getting the initial state) and event-sourcing (getting the updates). Therefore I am going to adjust my proposal for possible solutions to those four ones:

## 1. Keep mixing synchronous requests and event-sourcing
This is equal to the simple solution form my initial post. As the issue only occurs after a (re)start of the scheduler, one could argue that those issues are rare and therefore we can accept short periods of inconsistent state of the scheduler. 
If we are starting multiple instances of the adapter service, this can lead to more inconsistencies because of #285.

## 2. Only synchronous state transfer
All state changes in the scheduler must originate from a synchronous REST request from the scheduler to the Adapter. This request can either request the full state of all datasources or the state of one datasource. The response gets then applied to the state of the scheduler. The scheduler can either perform these requests periodically or after receiving a datasource change event. It is important that the scheduler does not use any information from the change event content to update the state of the scheduler.

## 3. Event-Sourcing (only asynchronous state transfer)
Use a truly event-sourced system. This would require an event store so all events can be persisted. A mechanism to replay all old events is also needed, so the scheduler can be initialized with the current state. To really get this working we must replace RabbitMQ with Kafka.

## 4. Introduce a trigger domain
The issue can be solved if the scheduler maintains its own domain and data. This would require to extract the trigger configuration out of the datasource domain and create a new trigger domain. The scheduler would also get its own database and REST endpoints to create, update and delete triggers. 
This change would make it also possible for other services to register triggers.

**Comment by sonallux** [comment]
The conclusion from the discussion is that we go with the first solution and live with the fact that there might be a short period of time where the scheduler is in an inconsistent state.
