### ISSUE TITLE
Database change events can get published in the wrong order

### ISSUE THREAD

**Issue by sonallux** [jvalue/ods#285]
Currently, the databases are the single source of truth in what state the ODS is. For many database changes the corresponding services do publish change events via RabbitMQ. The problem is that the services do perform the publish and not the databases. Multiple simultaneous change requests to one service are getting ordered by the database (because of transactions) but that ordering can not be enforced by the services when publishing the change events. The ordering is lost because the response from the database goes through the network and then there is no way of synchronizing multiple simultaneous requests. RabbitMQ itself does guarantee an ordering, if messages are published on the same channel, flow through the same exchange and one queue and one outgoing channel. So as long a single service is used RabbitMQ can not be blamed.

### Multiple services instances
If we scale the service to multiple instances the issue might get clearer. But actually, there is not much difference between a single instance handling multiple requests or multiple instances handling each only one request. The database is still determining the ordering of the changes and the ordering is lost because multiple service instances can not maintain that order when publishing the events.

### Visualization
Here is a visualization of this issue. For better visualization, the image uses two instances of the same service, but the issue is the same if a single instance with multiple threads is used (Even our NodeJS services fit perfectly in this model, despite the fact that NodeJS is not multi-threaded). In the image two requests are made to change the value of `foo` in the database. The numbers before the text of the arrows indicate a timestamp. After the requests have been executed, the database has a value of `2` for `foo`. But the last delivered event has a value of `1` for `foo`

![Database-event-ordering](https://user-images.githubusercontent.com/13821543/101790241-8870cf80-3b02-11eb-9438-3cc41a5a5898.png)

### Solutions
- Do not scale a service to multiple instances, only use a single thread and only handle one request at a time. This will work, but it is not practical because it does not scale at all.
- Remove the CRUD databases and use event sourcing
- Assign for each domain object exactly one thread/instance that can update it. Changes to this domain object can only be performed by the chosen thread/instance. Because this thread/instance can only handle one connection at a time, the ordering from the database is preserved for this domain object. This does not preserve the ordering between different domain objects, but that should not be required.
- Move the publication of change events to the database. I have found a nice tool for that: [Debezium](https://debezium.io). It will read the database transaction log and publish an event for any row-level change. Unfortunately, it can only work with [Kafka](https://kafka.apache.org) as a message/event system.

### Conclusion
This issue got my intention because of the scheduler initialization issue (#284). It can currently only cause trouble for the scheduler and maybe the StorageMQ service because only for datasources and pipelines change events are published. But the scheduler definitely needs the datasource change events in the correct order so imports are triggered correctly.

There is not a simple solution to this problem. All feasible solution would require a lot of architectural refactoring, therefore I would like to discuss this in the next developer meeting. 

If there is anything unclear, please let me know. Please also have a look at the scheduler initialization issue #284 as there is some overlap.

**Comment by georg-schwarz** [comment]
Yeah, transactionally sending out events and writing to a database is not possible. One of the approaches you described is called the [transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html). I think for the sake of scalability this would be the best solution.

I think we could also develop a very simple application that scans a configured table for new entries and publishes them as events. Probably we would need some conventions, like one column represents the routing key, etc... But that would also be a valid approach because writing into the same database twice (config table + event outbox table) in one transaction is possible... Could also lead to a nice blog-post / small reusable open-source project that gains some attention to the ODS.

Let's discuss these approaches in the next dev meeting :)

**Comment by sonallux** [comment]
One could also just live with the fact that events can be out of order. But then event consumer can not use the events as the source of truth. For example, the scheduler must then always query the adapter for the current state after receiving a datasource change event.

**Comment by georg-schwarz** [comment]
Well, for this use case it might also be an option to use thin events.

We also might argue that this only has an effect if multiple users concurrently update the same entity. How likely is that? Probably not likely enough to make things more complex to fix it?

**Comment by sonallux** [comment]
There is actually another issue that arises because the database update and the publication of the change event are not inside an atomic transaction: Change events can get lost even if the database has been updated successfully. This can happen when the connection to RabbitMQ is not available, but the connection to the database. 

Ideally, in this case, nothing should happen if one of the systems is not available. The state change may only be applied if both systems are available because there might be services (for example the scheduler) which rely on the fact that for every change in the database a corresponding change event is published and that those events are in the right order. Those services will get into an inconsistent state with our current approach not using a transaction for updating the database and publishing messages. But because we are in a distributed system we can not build transactional guarantees around our current approach that the services are publishing the events.

Therefore I have come up with an updated list of possible solutions:
## 1. Stay with the current setup
Events are then only sent with **at most once** delivery guarantee. Then all event consumers must be aware of this and we must ensure that our user experience does not suffer because of that.

## 2. Event-Sourcing
Update to a truly event-sourced system. This would mean that state changes are only possible with events and we must remove all databases because the stream of events is not the source of truth. This would require an append-only event store so all events can be persisted. A mechanism to replay all old events is also needed, so the actual current state can always be reconstructed. To really get this working we must replace RabbitMQ with Kafka.

## 3. Use the [transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html)
All events are written to a special database table `OUTBOX` instead of being directly published to the message broker. This can happen in one database transaction with the actual data change. A second service will then periodically read the new events from the `OUTBOX` database table and publish the events to the message broker

## 4. Change data capture
This is similar to 3. but there is not a special `OUTBOX` table. Instead, the events are generated directly from the database transaction log. [Debezium](https://debezium.io) is a great open-source tool by RedHat that does exactly this. It can run as a standalone service, but then it can only publish events to Kafka. And one can embed it in a Java service with the [Debezium Engine](https://debezium.io/documentation/reference/1.3/development/engine.html) library, then we can write a custom event handler that publishes the events to RabbitMQ. The Debezium Engine does only guarantee **at least once** while the standalone Debezium platform does guarantee **exactly once** event delivery.

Note: Debezium can also be used to implement solution 3. because one can filter the database tables Debezium listens to. We would then need to configure the filter and then only events for the `OUTBOX` table are produced.

**Comment by sonallux** [comment]
The conclusion from the discussion is that we try the transactional outbox pattern with our own little service using the Debezium Engine to publish the events using RabbitMQ.

**Comment by sonallux** [comment]
This issue is fixed by adding the adapter outboxer #307 and pipeline outboxer #311
