### ISSUE TITLE
Windows line endings

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/ods#303]
Seems like after checking out on Windows some line feeds don't match. Probably we should adapt the `.gitattributes` file accordingly.

**Comment by MBuchalik** [comment]
A .gitattributes file with this content could (!) help:

```
* text=auto eol=lf
```

**Comment by Kexplx** [comment]
Yeah, sounds familiar (#259). We applied unix line endings only to Dockerfiles, that fixed my problems back then.

Martins code should enforce this for all files and fix this tedious problem once and for all.
