### ISSUE TITLE
RabbitMQ 3.9 requires configuration using file, not environment variables

### ISSUE THREAD

**Issue by lunedis** [jvalue/ods#347]
We are currently using the RabbitMQ-image in version `rabbitmq:3-management-alppine`.

Starting from version 3.9, RabbitMQ no longer supports being configured using environment variables.

See this rabbitmq docker issue: https://github.com/docker-library/rabbitmq/issues/508

**Comment by georg-schwarz** [comment]
Suggested hotfix: specify version `rabbitmq:3.8.19-management-alpine`
Update to `latest` again after we fixed the issue and provided a conf file.
