### ISSUE TITLE
CDC Test and Pact Readme

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/ods#360]
As a contributor I'd like to have a Readme where I can learn about the cdc setup with pact in order to have a fast introduction into the topic.

Is should contain:
• What are cdc tests
• How to run them
• Where to find them in the project
• Steps to update and create them

@felix-oq

**Comment by felix-oq** [comment]
@georg-schwarz Please take a look at this draft: https://github.com/felix-oq/open-data-service/blob/cdct-improve-workflows/doc/consumer-driven-contract-testing/README.md

Does it cover the topics detailed enough? Is the location of the Readme within the project fine?

**Comment by georg-schwarz** [comment]
Looks good! Location is also fine.

Maybe add a little section with comparison to integration tests? Or what they test and what they don't test?

**Comment by felix-oq** [comment]
@georg-schwarz By now, the issue should be solved by the PR #368
