### ISSUE TITLE
UI StorageView broken

### ISSUE THREAD

**Issue by f3l1x98** [jvalue/ods#382]
The StorageViewItem of the UI does not display any data with the following error shown in the console:
![image](https://user-images.githubusercontent.com/52160939/141070398-ead2c353-46d2-40b8-9542-6cdbc37b9746.png)

**Comment by f3l1x98** [comment]
From my experimenting I found out, that this is most likely caused by a missing update after the data is retrieved from the backend.
For example adding `this.$forceUpdate();` after `this.item` has been set here https://github.com/jvalue/ods/blob/1eef1a7e91ac5b26ae0317329941a1e462385604/ui/src/storage/StorageItemView.vue#L61-L66

**Comment by georg-schwarz** [comment]
Following the `async/await` syntax instead of `promise.then` might already fix that problem.

**Comment by f3l1x98** [comment]
> Following the `async/await` syntax instead of `promise.then` might already fix that problem.

That unfortunately does not work as well (still needs the forced update)
But I managed to get it working by using the `key` html attribute, updating only the part that displays the item:
https://github.com/jvalue/ods/blob/b9b42e64d5aa03f7a99a8a44048afaea7ac9ed8c/ui/src/storage/StorageItemView.vue#L71-L82
https://github.com/jvalue/ods/blob/b9b42e64d5aa03f7a99a8a44048afaea7ac9ed8c/ui/src/storage/StorageItemView.vue#L5-L18
