### ISSUE TITLE
Storage MQ query timeout

### ISSUE THREAD

**Issue by knusperkrone** [jvalue/ods#401]
@georg-schwarz 
Creating a new Pipeline in the ODS Kubernetes cluster fails silently, as Storage-MQ throws this error:

```
[Query] "CREATE TABLE IF NOT EXISTS "public"."2094" (
  "id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
  "data" jsonb NOT NULL,
  "timestamp" timestamp,
  "pipelineId" bigint,
  CONSTRAINT "Data_pk_public_2094" PRIMARY KEY (id)
  )" with values [] failed: Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/app/node_modules/pg-pool/index.js:197:27)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Failed to handle 'pipeline.config.created' message: Error: timeout exceeded when trying to connect
```

It's important to note, that the call returns almost instantly and the service is successfully connected to the database.

**Comment by knusperkrone** [comment]
```json
statement_timeout: 10000
```

Maybe just adding this into the pg-dry-run package and updating dependencies should fix the issue?

**Comment by georg-schwarz** [comment]
Is it already solved? Asking because you closed the issue again.

**Comment by knusperkrone** [comment]
This was my first guess for the bug. But it's actual the missing postgrest config fixed in my pr
