### ISSUE TITLE
Reload UI sites

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/ods#58]
In #56 we already made the first step towards make the UI reloadable on every site.

Top-level reloading on e.g. `/datasources` works now, but not to `datasources/new`.
So I guess, therefore, the issue is somewhere else? Any guesses?

_Originally posted by @georg-schwarz in https://github.com/jvalue/open-data-service/pull/56#issuecomment-619812282_

**Comment by lunedis** [comment]
I just did some debugging.

The issue is probably with the vuejs-application itself and not the nginx deployment.
If you start up the auth and edge services separately and use `npm run serve` to run the UI locally, the error still occurs.

I'll keep working on it.
