### ISSUE TITLE
Integration tests and rabbitMQ

### ISSUE THREAD

**Issue by mathiaszinnen** [jvalue/ods#87]
We need to decide on how to perform end to end tests using rabbitMQ instead of http calls, suggestions for frameworks etc. are welcome

**Comment by georg-schwarz** [comment]
For integration-tests I suggest to start up a rabbit-mq instance and use it via the test code.
Publishing and subscribing to topics should do the job here I guess?

**Comment by georg-schwarz** [comment]
For unit testing, we probably want to mock the AMQP interface via usual mocking frameworks

**Comment by georg-schwarz** [comment]
Added first version in #128 for integration testing.
Seems to work just fine.
One *important learning* is to close the connection to AMQP in a tear-down method, otherwise the Docker container won't stop and the GitHub Action will get stuck!
